# should set environment variables using export


# This should be the last line of .bash_profile
test -r ~/.bashrc && . ~/.bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
